import type { Metadata } from "next";
import "../globals.css";
import Navbar from "@/components/Layout/Navbar";
import CustomProvider from "@/layouts/CustomProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <CustomProvider>
      {children}
    </CustomProvider>
  );
}
